version: '3'
services:
  keycloak:
    image: registry.cn-shanghai.aliyuncs.com/happiness-frog/keycloak:23.0.7
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Cttic@ky@2024
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=Cttic@ky@2024
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_HOSTNAME=keycloak.intl.ctticyun.com
    command: start-dev
    ports:
      - 8080:8080
      - 8443:8443
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=Cttic@ky@2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
