version: '2'
services:
  keycloak:
    image: registry.cn-shanghai.aliyuncs.com/happiness-frog/keycloak:12.0.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=keycloak-mysql
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=keycloak
#      - ROOT_LOGLEVEL=DEBUG
    ports:
      - 8080:8080
    volumes:
      - ./volumes/keycloak/realm-config:/opt/jboss/keycloak/realm-config

  keycloak-mysql:
    extends:
      file: mysql.yml
      service: keycloak-mysql
